[pytest]
filterwarnings =
    ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*:DeprecationWarning
    ignore:unclosed database:ResourceWarning
    ignore:builtin type Swigpy.*:DeprecationWarning:fitz
    ignore:builtin type SwigPy.*:DeprecationWarning
    ignore:builtin type swigvarlink.*:DeprecationWarning
