"""add groups speltakken memberships

Revision ID: 63f0c6ea2f45
Revises: 9f5c7199cc32
Create Date: 2026-04-21 15:10:43.428342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '63f0c6ea2f45'
down_revision: Union[str, Sequence[str], None] = '9f5c7199cc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('speltakken',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speltakken_group_id'), 'speltakken', ['group_id'], unique=False)
    op.create_table('membership_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('speltak_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['speltak_id'], ['speltakken.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_requests_group_id'), 'membership_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_membership_requests_speltak_id'), 'membership_requests', ['speltak_id'], unique=False)
    op.create_index(op.f('ix_membership_requests_user_id'), 'membership_requests', ['user_id'], unique=False)
    op.create_table('speltak_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('speltak_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['speltak_id'], ['speltakken.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speltak_memberships_speltak_id'), 'speltak_memberships', ['speltak_id'], unique=False)
    op.create_index(op.f('ix_speltak_memberships_user_id'), 'speltak_memberships', ['user_id'], unique=False)
    # Drop ix_users_email before batch_alter_table if it already exists on
    # databases created via create_all() — the batch operation will recreate it.
    bind = op.get_bind()
    existing_indexes = {idx['name'] for idx in inspect(bind).get_indexes('users')}
    if 'ix_users_email' in existing_indexes:
        op.drop_index('ix_users_email', table_name='users')

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('email', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_foreign_key('fk_users_created_by_id', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_created_by_id', type_='foreignkey')
        batch_op.drop_index('ix_users_email')
        batch_op.alter_column('email', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column('created_by_id')
    op.drop_index(op.f('ix_speltak_memberships_user_id'), table_name='speltak_memberships')
    op.drop_index(op.f('ix_speltak_memberships_speltak_id'), table_name='speltak_memberships')
    op.drop_table('speltak_memberships')
    op.drop_index(op.f('ix_membership_requests_user_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_speltak_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_group_id'), table_name='membership_requests')
    op.drop_table('membership_requests')
    op.drop_index(op.f('ix_speltakken_group_id'), table_name='speltakken')
    op.drop_table('speltakken')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
